"""
Path configuration for the project.
UPDATED for IEEE TCSVT Submission Structure.
"""

from pathlib import Path

# Project root directory (assumes this file is in new/configs/)
# .. -> new/
# .. -> ABR-Awareness-main/ (Root)
PROJECT_ROOT = Path(__file__).parent.parent

# Data directories
DATA_DIR = PROJECT_ROOT / 'data'
RAW_VIDEOS_DIR = DATA_DIR / 'raw_videos'
ENCODED_VIDEOS_DIR = DATA_DIR / 'encoded_videos'
VMAF_SCORES_DIR = DATA_DIR / 'vmaf_scores'
CONTENT_FEATURES_DIR = DATA_DIR / 'content_features'

# --- NEW STANDARDIZED PATHS (Generated by organize_data.py) ---
STANDARDIZED_DIR = DATA_DIR / 'standardized'
TRAIN_TRACES_DIR = STANDARDIZED_DIR / 'train_traces'  # For Training (FCC)
TEST_TRACES_DIR = STANDARDIZED_DIR / '5g_test_traces_json'    # For Evaluation (Norway + Test FCC)

# Fallback for legacy scripts (optional)
# NETWORK_TRACES_DIR = DATA_DIR / 'network_traces'

# Results directories
RESULTS_DIR = PROJECT_ROOT / 'results'
MODELS_DIR = RESULTS_DIR / 'models'
LOGS_DIR = RESULTS_DIR / 'logs'
PLOTS_DIR = RESULTS_DIR / 'plots'

# Create output directories if they don't exist
for directory in [RESULTS_DIR, MODELS_DIR, LOGS_DIR, PLOTS_DIR]:
    directory.mkdir(parents=True, exist_ok=True)


def get_paths():
    """Get all paths as a dictionary."""
    return {
        'project_root': PROJECT_ROOT,
        'data_dir': DATA_DIR,
        'raw_videos': RAW_VIDEOS_DIR,
        'encoded_videos': ENCODED_VIDEOS_DIR,
        'vmaf_scores': VMAF_SCORES_DIR,
        'content_features': CONTENT_FEATURES_DIR,
        
        # --- CRITICAL UPDATES ---
        # Scripts using 'processed_traces' will now default to TRAIN traces
        # But explicit keys for train/test are added for advanced scripts
        'processed_traces': TRAIN_TRACES_DIR, 
        
        'train_traces': TRAIN_TRACES_DIR,  # Use this for training loop
        'test_traces': TEST_TRACES_DIR,    # Use this for final evaluation
        
        'results': RESULTS_DIR,
        'models': MODELS_DIR,
        'logs': LOGS_DIR,
        'plots': PLOTS_DIR
    }


if __name__ == '__main__':
    """Test paths and verify data existence."""
    print("\n📁 Project Paths Verification:\n")
    paths = get_paths()
    
    all_good = True
    for name, path in paths.items():
        exists = path.exists()
        icon = "✓" if exists else "✗"
        print(f"{icon} {name:20s}: {path}")
        
        if not exists and name in ['train_traces', 'test_traces']:
            all_good = False
            
    print("-" * 50)
    if not all_good:
        print("⚠ WARNING: Standardized data directories are missing!")
        print("  Please run 'python organize_data.py' first to generate them.")
    else:
        print(f"✓ Data found!")
        print(f"  - Training samples: {len(list(paths['train_traces'].glob('*.json')))}")
        print(f"  - Testing samples:  {len(list(paths['test_traces'].glob('*.json')))}")
        print("  Ready for training.")